language: node_js
cache:
  directories:
    - $HOME/.npm

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

jobs:
  include:
    - node_js: 4
    - node_js: 6
    - node_js: 8
    - node_js: 9
      script:
        - npm run test
        - npm run coverage
    - stage: release
      node_js: lts/*
      script:
        - npm run semantic-release

stages:
  - test
  - name: release
    if: branch = master
